edited the html check

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -35,4 +35,6 @@ jobs:
 
       - name: Basic Syntax & Structure Check
         run: |
-          grep -q "<html>" index.html && echo "HTML validated." || (echo "Invalid HTML structure" && exit 1)
+         - name: Basic Syntax & Structure Check
+        run: |
+          grep -iq "<html" index.html && echo "HTML validated." || (echo "Invalid HTML structure" && exit 1)
